### ISSUE TITLE
Piano mode

### ISSUE THREAD

**Issue by Niekxd** [mat1jaczyyy/lpp-performance-cfw#10]
AKAI recently released their FL Studio Fire device, and it has a really cool feature that it lays out the buttons like a piano in this way:
![image](https://user-images.githubusercontent.com/29899069/46244514-2ffcfe00-c3e0-11e8-92dc-871f7fe27e21.png)
The green keys are the C keys,
The purple keys are the white keys,
The orange keys are the black keys.

It would be really nice to see something like this implemented on the firmware so that music producers can create melodies and chords way more easier without buying an actual keyboard.
Cheers.

**Comment by mat1jaczyyy** [comment]
In the context of the Launchpad, do you think it would be better to have 8x2 panels for octaves? You will for sure need octave selector, but do you think it requires a transposition one (think left/right in note/scale mode)?

**Comment by Niekxd** [comment]
8x2 would be fine i guess, the transposition one is very interesting and i really like that idea.

**Comment by mat1jaczyyy** [comment]
This will almost certainly take a bit of time to implement. I will take a deeper look when I find some time to focus on it
