### ISSUE TITLE
Multiple color palettes

### ISSUE THREAD

**Issue by nyrkmusic** [mat1jaczyyy/lpp-performance-cfw#17]
supporting the ability to use multiple color palettes at the same time would allow for an even wider color variety. This could be done by assigned each color palette to an own midi channel so you can use multiple palettes at once when sending midi data to the launchpad out of multiple track, each with a different output channel
(e.g.
palette 1 -> ch. 14
palette 2 -> ch. 15
palette 3 -> ch. 16 )

**Comment by mat1jaczyyy** [comment]
Sounds overcomplicated, in my opinion, and the gain from it is minimal. I think this is best implemented on your own separate fork, and not something that could be built into the main firmware build for a few reasons:

1. It makes creating the lights in Ableton a lot more complicated, and harder to manage/work with.
2. Implementing it would likely confuse people who are used to switchable palettes in the firmware. This is something that's already established as a main feature.
3. If you really want to have this functionality right now, you can likely do it with 3 separate instances of Retina loaded.
