### ISSUE TITLE
Launchpad S

### ISSUE THREAD

**Issue by dekelm8** [mat1jaczyyy/lpp-performance-cfw#24]
Hey, this code can it the "Launchpad S" instead using the Pro ?

**Comment by Niekxd** [comment]
No

**Comment by dekelm8** [comment]
Thanks, do you know about any firmware that fit the "S"?

**Comment by mat1jaczyyy** [comment]
Hey @dekelm8, thanks for your interest! Novation have only released hardware resources for the Launchpad Pro, so we can't run custom firmware code on other Launchpads. Unless they release these at some point, no one can modify the code that runs on a Launchpad S or other models.
