### ISSUE TITLE
Dead notes when launchpad powered on in note mode

### ISSUE THREAD

**Issue by isaacVandermeulen** [mat1jaczyyy/lpp-performance-cfw#31]
When I turn on my launchpad and it is in note or drum mode, only a few of the buttons work and the others are dead. Switching to session mode and switching back to note mode fixes the problem but is annoying to do everytime I turn on my launchpad. The same thing also happens when I change the plugin used for the active track in Ableton

**Comment by mat1jaczyyy** [comment]
Sounds like you're using the Launchpad Pro control surface in Ableton for the Standalone port, you should only use it with the MIDI port.

**Comment by isaacVandermeulen** [comment]
That worked! Thanks for your help
