### ISSUE TITLE
Port components fader to fader mode

### ISSUE THREAD

**Issue by SimplyMerlin** [mat1jaczyyy/lpp-performance-cfw#34]
Okay so,
while playing around with the fader in the custom components i noticed that it is quite different to the default fader mode with different brightnesses for more specific results.

I think it would be a nice enhancement to port a fader similar to that to the fader mode too as the default or as a setting.

Video showing off what I mean: https://streamable.com/3z237a

**Comment by mat1jaczyyy** [comment]
I want to keep Fader mode true to the stock Pro experience. Though, a setting might work out...

**Comment by mat1jaczyyy** [comment]
Live mode depends on Fader mode.



no.
