### ISSUE TITLE
Port configuration 

### ISSUE THREAD

**Issue by TheLifeGamingYT** [mat1jaczyyy/lpp-performance-cfw#4]
When i configure the ports, the names become red and it doesn't let me use those
https://imgur.com/a/zprq16e

**Comment by TheLifeGamingYT** [comment]
Just needed to restart launchpad.

**Comment by mat1jaczyyy** [comment]
this is because the novation usb driver doesn't support the open firmware and you have another app using the launchpad at the moment. close all other apps that use the launchpad.﻿
