### ISSUE TITLE
(Chord Mode) While deleting chords in chords mode all lights are flashing extremely bright 

### ISSUE THREAD

**Issue by rasch3n** [mat1jaczyyy/lpp-performance-cfw#43]
If I delete saved chords on the MK3 nothing flashes at all.

**Comment by mat1jaczyyy** [comment]
Writing stuff to flash just does this on Pro. Probably because the PWM timer is frozen during the flash operation. Nothing I can do...

**Comment by rasch3n** [comment]
Ok good to know. But thank you anyway!
