### ISSUE TITLE
Custom modes: Horizontal faders broken in slots other than the first one

### ISSUE THREAD

**Issue by rasch3n** [mat1jaczyyy/lpp-performance-cfw#55]
As you can see in the picture, I set up a horizontal fader, but it is displayed vertically on the launchpad and does not work. However, if I have another project in the first slot, the faders are displayed correctly there.

[setup.zip](https://github.com/mat1jaczyyy/lpp-performance-cfw/files/6257605/setup.zip)
![Loaded Mode CCNotes-Ch11 20c](https://user-images.githubusercontent.com/68027981/113563454-01db8300-9608-11eb-90c2-1d11363c5416.jpeg)

**Comment by rasch3n** [comment]
In the zip file are my setup files named by the index where I have them on my launchpad

**Comment by mat1jaczyyy** [comment]
works if loaded into slot 1, broken in other slots
