### ISSUE TITLE
[Custom Modes] MIDI notes sent on Channel 1 received as a remote-control assignment

### ISSUE THREAD

**Issue by pnxl** [mat1jaczyyy/lpp-performance-cfw#72]
### Description
When setting a MIDI note to send on Channel 1 or Global Channel in Novation Components then flashing it, Live receives it as a remote-control assignment instead of a standard MIDI on/off message - no inputs are being received despite having record arm on and receiving all inputs.

### Reproduction
- Create a new custom mode that has a MIDI note button, any note, set to Ch 1 or Global.
- Import to Launchpad
- You'll see that Live doesn't receive it as a standard MIDI on/off message.

**Comment by mat1jaczyyy** [comment]
I'm assuming you're using a Control Surface with the MIDI port in Ableton Live.

If you want notes to come in raw without triggering Control Surface events first, you'll need to disable the Control Surface for that port.

**Comment by pnxl** [comment]
but the custom modes come through the standalone port no? and the MIDI port is only used for Live mode?

**Comment by mat1jaczyyy** [comment]
The port name is just a name, Live mode doesn't really exist on the Launchpad but rather most of it is rendered PC-side by Ableton (this is what a Control Surface is).

So pls make sure you're not using a Control Surface with your standalone port.

**Comment by pnxl** [comment]
awesome, thanks! for anyone else reading this: if live keeps assigning your standalone port to the Pro's control surface, just uncheck the remote box for your standalone port

**Comment by mat1jaczyyy** [comment]
resolved
