### ISSUE TITLE
Not able to import .syx file onto LaunchPad Utility 

### ISSUE THREAD

**Issue by markusjellyfish** [mat1jaczyyy/lpp-performance-cfw#76]
Hi 
I'm trying to load a Launchpad X user layout onto a LaunchPad Pro via your (web based) LaunchPad Utility. I have installed your Firmware on the LP Pro. I exported the LPX user mode .syx file to my desktop but when trying to import to your LP Utility, I keep getting the following message : 
Invalid File Mode : Error : Data
... any tips what I might be doing wrong ? .... I have attached the zipped.  .syx file 

I'm using 
AppleMacBookPro M2. / 13.6.9
Chrome 131.0.6778.109 
Components Version 1.54.0 (1.54.0)
[MDx.syx.zip](https://github.com/user-attachments/files/18053092/MDx.syx.zip)

kind regards Markus

**Comment by mat1jaczyyy** [comment]
Custom Modes were updated by Novation and I haven't found the time yet to update. Sorry :/
Soon:tm:

there's an issue for it already https://github.com/mat1jaczyyy/lpp-performance-cfw/issues/71
