### ISSUE TITLE
Add support for mode light

### ISSUE THREAD

**Issue by TheLifeGamingYT** [mat1jaczyyy/lpp-performance-cfw#9]
Hello, I'm back again (I'm sorry mat if I'm stressing you)!
I wanted to ask you if you could add support for the pro mode light in your CFW.
But only support for mode light but even add the feature to listen to the solo light and synchronize it to the mode light like shown in this video: https://www.youtube.com/watch?v=2-BxZaxdY8Y
Probably this could be a big feature to add as for right now we need external max patches but as this CFW doesn't support max then if you add it, will be a game-changer!
Thanks bro

**Comment by Niekxd** [comment]
fam you can already do that iirc

**Comment by TheLifeGamingYT** [comment]
How?

**Comment by mat1jaczyyy** [comment]
Mode light is accessible in Performance mode on D#0 in Drum Rack layout and on 99 in XY layout. If you want to synchronize it to any of the circle or square buttons, create a MIDI Effect Rack that does so.

**Comment by TheLifeGamingYT** [comment]
Sorry I didn't know that

**Comment by TheLifeGamingYT** [comment]
Ok but how do I create it

**Comment by TheLifeGamingYT** [comment]
(sorry I don't know much about midi effects in Ableton)

**Comment by mat1jaczyyy** [comment]
that falls outside the scope of this issue.
